apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins-slave-nodejs-rhel7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7:latest
      generation: 1
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7:v3.3
      generation: 1
      importPolicy:
        scheduled: true
      name: v3.3
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7:v3.4
      generation: 1
      importPolicy:
        scheduled: true
      name: v3.4
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7:v3.5
      generation: 1
      importPolicy:
        scheduled: true
      name: v3.5
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7:v3.6
      generation: 1
      importPolicy:
        scheduled: true
      name: v3.6
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins-slave-maven-rhel7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7:latest
      generation: 1
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7:v3.3
      generation: 1
      importPolicy:
        scheduled: true
      name: v3.3
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7:v3.4
      generation: 1
      importPolicy:
        scheduled: true
      name: v3.4
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7:v3.5
      generation: 1
      importPolicy:
        scheduled: true
      name: v3.5
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7:v3.6
      generation: 1
      importPolicy:
        scheduled: true
      name: v3.6
      referencePolicy:
        type: Source
